openapi: 3.0.3

info:
  title: Calendar application
  description: project that will help you to manage your time
  version: 1.0.0

# just an example
paths:
  /pets:
    get:
      description: Returns all pets from the system that the user has access to
      responses:
        '200':
          description: A list of pets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'

components:
  schemas:
    pet:
      type: object
      properties:
        name:
          type: string
          description: Pet name
