spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    hikari:
      jdbc-url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}